"""Garment recognition package exports."""

from models.garment_recognition.confidence import (
    DEFAULT_REVIEW_THRESHOLD,
    ConfidenceSummaryItem,
    DetectedProperty,
    detected,
)
from models.garment_recognition.contract import (
    GARMENT_RECOGNITION_CONTRACT_VERSION,
    GARMENT_RECOGNITION_SCHEMA_VERSION,
    GarmentRecognitionContract,
)
from models.garment_recognition.enums import (
    BrandingRegionKind,
    DetectedCollarStyle,
    DetectedSleeveConstruction,
    GarmentType,
    PanelRole,
    PatternFamily,
    RecognitionModuleId,
    RecognitionStatus,
    SegmentationRegionId,
    StripeOrientation,
    StripeSymmetry,
    StripeTermination,
)
from models.garment_recognition.mapping import (
    GAMECHANGER_PRODUCTION_TEMPLATE_ID,
    GAMECHANGER_VNECK_COLLAR_ID,
    map_collar,
    map_pattern_family,
    map_sleeve,
    map_stripe_orientation,
)
from models.garment_recognition.module import (
    ModuleResult,
    RecognitionContext,
    RecognitionModule,
    RecognitionModuleBase,
)
from models.garment_recognition.projection import (
    BRANDING_SPEC_FIELDS,
    RECOGNITION_PROJECTABLE_FIELDS,
    apply_contract_to_design_spec,
    assert_no_branding_leak,
    build_design_spec_updates,
)
from models.garment_recognition.sections import (
    BoundingBox,
    BrandingExclusion,
    BrandingSection,
    CollarSection,
    ColourSection,
    GarmentSection,
    PanelObservation,
    PanelSection,
    PatternSection,
    PolygonRegion,
    SegmentedRegion,
    SegmentationSection,
    SleeveSection,
    StripeSection,
)

__all__ = [
    "BRANDING_SPEC_FIELDS",
    "DEFAULT_REVIEW_THRESHOLD",
    "GARMENT_RECOGNITION_CONTRACT_VERSION",
    "GARMENT_RECOGNITION_SCHEMA_VERSION",
    "GAMECHANGER_PRODUCTION_TEMPLATE_ID",
    "GAMECHANGER_VNECK_COLLAR_ID",
    "RECOGNITION_PROJECTABLE_FIELDS",
    "BoundingBox",
    "BrandingExclusion",
    "BrandingRegionKind",
    "BrandingSection",
    "CollarSection",
    "ColourSection",
    "ConfidenceSummaryItem",
    "DetectedCollarStyle",
    "DetectedProperty",
    "DetectedSleeveConstruction",
    "GarmentRecognitionContract",
    "GarmentSection",
    "GarmentType",
    "ModuleResult",
    "PanelObservation",
    "PanelRole",
    "PanelSection",
    "PatternFamily",
    "PatternSection",
    "PolygonRegion",
    "RecognitionContext",
    "RecognitionModule",
    "RecognitionModuleBase",
    "RecognitionModuleId",
    "RecognitionStatus",
    "SegmentedRegion",
    "SegmentationRegionId",
    "SegmentationSection",
    "SleeveSection",
    "StripeOrientation",
    "StripeSection",
    "StripeSymmetry",
    "StripeTermination",
    "apply_contract_to_design_spec",
    "assert_no_branding_leak",
    "build_design_spec_updates",
    "detected",
    "map_collar",
    "map_pattern_family",
    "map_sleeve",
    "map_stripe_orientation",
]
